name = "url-to-kindle-worker"
main = "dist/index.bundled.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
# Add your environment variables here
# RESEND_API_KEY will be set via wrangler secret

[build]
command = "cd ../.. && npx turbo build"